/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#ffb2b7',
        'surface-tint': '#ffb3b6',
        'on-secondary-fixed-variant': '#92002a',
        error: '#ffb4ab',
        'primary-fixed-dim': '#ffb3b6',
        'on-error': '#690005',
        'on-surface-variant': '#e5bdbe',
        'on-primary': '#68001a',
        'tertiary-fixed': '#ffd9dd',
        'on-tertiary-container': '#fffaf9',
        'on-background': '#e3e1e9',
        'tertiary-fixed-dim': '#ffb2bd',
        'primary-container': '#e11d48',
        'on-secondary': '#67001b',
        'surface-container-high': '#292a2f',
        'on-secondary-container': '#ffc2c4',
        'outline-variant': '#5c3f40',
        'inverse-surface': '#e3e1e9',
        'tertiary-container': '#c74563',
        'inverse-primary': '#be0037',
        'inverse-on-surface': '#2f3036',
        surface: '#121318',
        'on-primary-fixed': '#40000c',
        'surface-container-highest': '#34343a',
        'surface-container': '#1e1f25',
        'on-tertiary-fixed': '#400014',
        'on-surface': '#e3e1e9',
        'surface-variant': '#34343a',
        'surface-dim': '#121318',
        'surface-container-lowest': '#0d0e13',
        outline: '#ac8889',
        secondary: '#ffb2b7',
        'on-tertiary': '#670024',
        'on-primary-container': '#fffaf9',
        primary: '#ffb3b6',
        'surface-bright': '#38393f',
        'secondary-container': '#b50036',
        'on-primary-fixed-variant': '#920028',
        background: '#121318',
        'surface-container-low': '#1a1b21',
        'on-secondary-fixed': '#40000d',
        'error-container': '#93000a',
        'primary-fixed': '#ffdada',
        'secondary-fixed': '#ffdadb',
        tertiary: '#ffb2bd',
        'on-tertiary-fixed-variant': '#8a1538',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'space-sm': '0.75rem',
        'space-md': '1.25rem',
        margin: '2.5rem',
        'space-xl': '3.5rem',
        'space-xs': '0.375rem',
        'margin-mobile': '1.25rem',
        'gutter-mobile': '1rem',
        'space-lg': '2rem',
      },
      fontFamily: {
        'metric-val': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Space Grotesk', 'sans-serif'],
        'label-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'display-mobile': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'metric-val': ['2.25rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['0.9375rem', { lineHeight: '1.55', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', letterSpacing: '-0.01em', fontWeight: '400' }],
        display: ['4.5rem', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg': ['3rem', { lineHeight: '1.15', letterSpacing: '-0.025em', fontWeight: '700' }],
        'label-md': ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-lg': ['0.875rem', { lineHeight: '1.25', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-lg-mobile': ['2rem', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['2rem', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['1.375rem', { lineHeight: '1.35', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-mobile': ['2.75rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
